name: call another workflow
on: 
  push:
    branches:
        - 'main'
jobs:
  feature-pipeline:
    #this is calling centralized workflow
    uses: workflows-git/workflows/.github/workflows/nodejs-eks-feature.yaml@main  # Reference local path if in the same repository
    #sending parameters
    with:
      project: 'roboshop' 
      component: 'catalogue'